### ISSUE TITLE
“Download press kit” link does not work

### ISSUE THREAD

**Issue by KrzysiekJ** [tootsuite/joinmastodon#18] opened 2017-07-05 17:43 UTC
It just points to the top of page (“#”).

**Comment by Sylvhem** [comment] 2017-07-09 15:58
I can reproduce this with Mozilla Firefox 54.0 64 bits on Ubuntu 17.04.

**Comment by Gargron** [comment] 2017-07-09 21:06
Not implemented yet.

**Comment by koyuawsmbrtn** [comment] 2017-07-26 07:32
This seems to be implemented now. We can close this issue.

**Closed** 2017-07-26 07:35 UTC
